eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
eureka.instance.prefer-ip-address : true
eureka.instance.client.registerWithEureka: true
eureka.instance.client.fetchRegistry: true
spring.application.name : USER-SERVICE

eureka:
 instance:
  prefer-ip-address: true
 client:
  registerWithEureka: true
  fetchRegistry: true
  service-url:
   defaultZone: http://localhost:8761/eureka/
